.\" Process this file with
.\" groff -man -Tutf8 batarim-console.man
.\"
.TH BATARIM-CONSOLE 1 "October 2011" Batarim "User Manuals"
.SH NAME
batarim-console \- dump current system resource usage metrics to stdout
.br
batarim-logger \- dump system resource usage metrics to stdout in csv format
.SH SYNOPSIS
.B batarim-console
.br
.B batarim-logger
.SH DESCRIPTION
.B batarim-console
and
.B batarim-logger
dumps current system resource usage metrics to stdout (batarim-logger dumps \
them in csv format). These metrics include the current date and time, uptime, \
processor usage, RAM usage, focused window CPU and RAM usage, the processes \
with the highest CPU and RAM usages along with their CPU and RAM usages.
.SH AUTHOR
Written by
.MT jeff@beyondtechnicallycorrect.com
Jeffrey Charles
.ME
.SH REPORTING BUGS
Report bugs to
.MT jeff@beyondtechnicallycorrect.com
Jeffrey Charles
.ME
.SH COPYRIGHT
Copyright \(co 2011 Jeffrey Charles. License BSD. There is NO WARRANTY, to \
the extent permitted by law.
